services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    restart: unless-stopped

  migrate:
    build: .
    command: npx prisma migrate deploy
    env_file:
      - .env.local
    restart: 'no'
